#! /usr/bin/env python
# encoding: utf-8

search_path = []

if not bld.is_mkspec_platform('windows'):
    search_path = ['.']

bld.program(
    features='cxx',
    source=['redirecting_receiver.cpp'],
    target='../../redirecting_receiver',
    rpath=search_path,
    use=['scorecpp_includes','links', 'boost_system'])

bld.program(
    features='cxx',
    source=['redirecting_sender.cpp'],
    target='../../redirecting_sender',
    rpath=search_path,
    use=['scorecpp_includes','links', 'boost_system'])
